abbrevs:
  # general
  ## What does '-l' stand for?
  - name: exec -l $SHELL
    abbr: reload
    snippet: exec -l $SHELL
    evaluate: true

  - name: trash
    abbr: del
    snippet: trash

  - name: ls
    abbr: ls
    snippet: ls --color=auto --literal

  - name: grep
    abbr: grep
    snippet: grep --color=auto

  ## Do not replace '-a' with '--append' because BSD script command
  ## does not support a long option
  - name: script
    abbr: script
    snippet: script -a

  - name: dirs
    abbr: dirs
    snippet: show_directory_stack

  - name: pushd
    abbr: p
    snippet: push_directory

  - name: popd
    abbr: pop
    snippet: pop_directory

  - name: bundle exec
    abbr: be
    snippet: bundle exec

  ## usage: usage: which cat | xargs -n 1 -o file
  - name: xargs
    abbr: xx
    snippet: xargs --max-args=1 --open-tty
    global: true

  - name: cron-apply
    abbr: ca
    snippet: cron-apply

  - name: internet-fasting-period
    abbr: ifp
    snippet: internet-fasting-period



  # git
  - name: git
    abbr: g
    snippet: git

  - name: git add
    abbr: ga
    snippet: git add

  - name: git add
    abbr: a
    snippet: add
    global: true
    context: '^git\s'

  - name: git add --all
    abbr: gaa
    snippet: git add --all

  - name: git add --all
    abbr: aa
    snippet: add --all
    global: true
    context: '^git\s'

  - name: git commit
    abbr: gc
    snippet: git commit

  - name: git commit
    abbr: c
    snippet: commit
    global: true
    context: '^git\s'

  - name: git status
    abbr: gst
    snippet: git status

  - name: git status
    abbr: s
    snippet: status
    global: true
    context: '^git\s'

  - name: git diff
    abbr: gd
    snippet: git diff

  - name: git diff
    abbr: d
    snippet: diff
    global: true
    context: '^git\s'

  - name: git checkout
    abbr: gco
    snippet: git checkout

  - name: git checkout
    abbr: co
    snippet: checkout
    global: true
    context: '^git\s'

  - name: git cherry-pick
    abbr: gcp
    snippet: git cherry-pick

  - name: git cherry-pick
    abbr: cp
    snippet: cherry-pick
    global: true
    context: '^git\s'

  - name: git up
    abbr: up
    snippet: push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
    evaluate: true
    global: true
    context: '^git\s'

  - name: git count
    abbr: count
    snippet: log --oneline | wc --lines
    global: true
    context: '^git\s'

  - name: git refresh
    abbr: gref
    snippet: touch $(git rev-parse --git-dir)/hooks/tmp && rm --recursive $(git rev-parse --git-dir)/hooks/* && git init
    evaluate: true



  # docker
  - name: docker
    abbr: d
    snippet: docker

  - name: docker compose
    abbr: dcom
    snippet: docker compose

  - name: docker compose
    abbr: c
    snippet: compose
    global: true
    context: '^docker\s'
