if [ -f ~/.env.preferences ]; then
  . ~/.env.preferences
fi

# These environment variables are changeable by ~/.env.preferences
export LSCOLORS=$(echo ${LSCOLORS-gxfxcxdxbxegedabagacad})
export HISTCONTROL=$(echo ${HISTCONTROL-ignoredups})
export HISTSIZE=$(echo ${HISTSIZE-1000000})
export LESS=$(echo ${LESS-'-iMNRS+10'}) # DO EDIT IN VIM because verbatim insert is used
export LESSOPEN=$(echo ${LESSOPEN-'| /usr/local/bin/src-hilite-lesspipe.sh  %s'})
## https://qiita.com/delphinus/items/b04752bb5b64e6cc4ea9
export LESS_TERMCAP_mb=$(echo ${LESS_TERMCAP_mb-$'\E[01;31m'})      # Begins blinking.
export LESS_TERMCAP_md=$(echo ${LESS_TERMCAP_md-$'\E[01;31m'})      # Begins bold.
export LESS_TERMCAP_me=$(echo ${LESS_TERMCAP_me-$'\E[0m'})          # Ends mode.
export LESS_TERMCAP_se=$(echo ${LESS_TERMCAP_se-$'\E[0m'})          # Ends standout-mode.
export LESS_TERMCAP_so=$(echo ${LESS_TERMCAP_so-$'\E[00;47;30m'})   # Begins standout-mode.
export LESS_TERMCAP_ue=$(echo ${LESS_TERMCAP_ue-$'\E[0m'})          # Ends underline.
export LESS_TERMCAP_us=$(echo ${LESS_TERMCAP_us-$'\E[01;32m'})      # Begins underline.
export EDITOR=$(echo ${EDITOR-vim})
export IGNOREEOF=$(echo ${IGNOREEOF-10000})
export RUBY_CONFIGURE_OPTS=$(echo ${RUBY_CONFIGURE_OPTS-"--with-openssl-dir=/usr/local/opt/openssl@1.1"})
export PKG_CONFIG_PATH=$(echo ${PKG_CONFIG_PATH-/usr/local/opt/imagemagick@6/lib/pkgconfig})
export NOTIFICATION_PERIOD_THRESHOLD=$(echo ${NOTIFICATION_PERIOD_THRESHOLD-180})
export NOTIFICATION_SOUND=$(echo ${NOTIFICATION_SOUND-Funk})
export SESSION_LOG_PATH=$(echo ${SESSION_LOG_PATH-$HOME/.log/typescript})
export SESSION_LOG_SIZE=$(echo ${SESSION_LOG_SIZE-100000})
export POKEMON_SLIDESHOW_DURATION=$(echo ${POKEMON_SLIDESHOW_DURATION-7})
export POKEMON_DARK_THRESHOLD=$(echo ${POKEMON_DARK_THRESHOLD-0.5})

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

export PATH
export MANPATH
export DOTPATH
export PROMPT_COMMAND
export SCRIPT_PS1

# Save the history in correct order
shopt -u histappend

# Auto correct and continue to run cd command even if directory name is misspelled partly
#
# disable because this is rarely used
#shopt -s cdspell

# Change directories without `cd`
# NOTE: bash version more than 4.0 is required
#
# On macOS, simply run:
# $ brew install bash
# $ echo /usr/local/bin/bash | sudo tee -a /etc/shells
# $ chpass -s /usr/local/bin/bash
# (Type your password, then reboot your shell application)
#
# somehow this does not work on bash 5.0.11
# though trying above command
# this works on company MacBook Pro
# but does not work on personal MacBook Pro (bash 5.0.11)
#shopt -s autocd

# Record output in terminal
case "${OSTYPE}" in
  darwin*)
    if [ ! -d $SESSION_LOG_PATH ]; then
      mkdir -p $SESSION_LOG_PATH
    fi

    if [[ "$(ps -e -o pid,command | grep -E "^\s{0,}$PPID" | grep -v grep)" =~ "login" ]]; then
      script -a -F $SESSION_LOG_PATH/recording.log
    fi
  ;;
  linux*)
    : # TODO (MEMO: use -f option instead of -F on GNU script command)
  ;;
esac

# Below here may not be executed because the command 'script' forks the shell
