tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "rcmdnk/rcmdnkpac"
brew "anyenv"
brew "bash"
brew "bash-completion"
brew "bat"
brew "binutils"
brew "icu4c"
brew "boost"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "fd"
brew "findutils"
brew "freetype"
brew "ghq"
brew "git"
brew "readline"
brew "gnu-getopt"
brew "gnu-sed"
brew "imagemagick"
brew "imagemagick@6"
brew "jq"
brew "libmagic"
brew "lsd"
brew "mas"
brew "peco"
brew "pkg-config"
brew "ripgrep"
brew "rmtrash"
brew "source-highlight"
brew "starship"
brew "terminal-notifier"
brew "tree"
brew "v8@3.15"
brew "rcmdnk/rcmdnkpac/rcmdnk-trash"
cask "alfred"
cask "appcleaner"
cask "evernote"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "keyboardcleantool"
cask "scroll-reverser"
cask "slack"
cask "soundflower"
cask "streamlabs-obs"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "BetterSnapTool", id: 417375580
mas "GarageBand", id: 682658836
mas "Gifted", id: 771955779
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LadioCast", id: 411213048
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PicGIF", id: 784260229
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
