if [ -d ~/.env.preferences ]; then
  for FILE in ~/.env.preferences/*; do . $FILE; done
fi

# These environment variables are changeable by ~/.env.preferences
export LSCOLORS=$(echo ${LSCOLORS-gxfxcxdxbxegedabagacad})
export HISTCONTROL=$(echo ${HISTCONTROL-ignoredups})
export HISTSIZE=$(echo ${HISTSIZE-""})
export HISTFILESIZE=$(echo ${HISTFILESIZE-""})
export LESS=$(echo ${LESS-'-iMNRS+10'}) # DO EDIT IN VIM because verbatim insert is used
## https://qiita.com/delphinus/items/b04752bb5b64e6cc4ea9
export LESS_TERMCAP_mb=$(echo ${LESS_TERMCAP_mb-$'\E[01;31m'})      # Begins blinking.
export LESS_TERMCAP_md=$(echo ${LESS_TERMCAP_md-$'\E[01;31m'})      # Begins bold.
export LESS_TERMCAP_me=$(echo ${LESS_TERMCAP_me-$'\E[0m'})          # Ends mode.
export LESS_TERMCAP_se=$(echo ${LESS_TERMCAP_se-$'\E[0m'})          # Ends standout-mode.
export LESS_TERMCAP_so=$(echo ${LESS_TERMCAP_so-$'\E[00;47;30m'})   # Begins standout-mode.
export LESS_TERMCAP_ue=$(echo ${LESS_TERMCAP_ue-$'\E[0m'})          # Ends underline.
export LESS_TERMCAP_us=$(echo ${LESS_TERMCAP_us-$'\E[01;32m'})      # Begins underline.
export EDITOR=$(echo ${EDITOR-vim})
export IGNOREEOF=$(echo ${IGNOREEOF-10000})
export RUBY_CONFIGURE_OPTS=$(echo ${RUBY_CONFIGURE_OPTS-"--with-openssl-dir=/usr/local/opt/openssl@1.1"})
export PKG_CONFIG_PATH=$(echo ${PKG_CONFIG_PATH-/usr/local/opt/imagemagick@6/lib/pkgconfig})
export GIT_FETCH_PERIOD_THRESHOLD=$(echo ${GIT_FETCH_PERIOD_THRESHOLD-180})
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

export DOTPATH=""
export PATH
export MANPATH

if type src-hilite-lesspipe.sh 1>/dev/null 2>/dev/null; then
  export LESSOPEN='| /usr/local/bin/src-hilite-lesspipe.sh  %s'
fi
