add_newline = true

[cmd_duration]
min_time = 0
show_milliseconds = true

[time]
disabled = true # Disable temporarily because I don't want to mind time
style = "#b0c4de"
time_format = "%Y/%m/%d %T"
format = "[$time]($style) "

[hostname]
style = "bold #ffa833"

[username]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
