add_newline = false

[cmd_duration]
min_time = 0
show_milliseconds = true

[env_var]
variable = "SCRIPT_PS1"
default = "???"
style = "bold yellow"

[time]
disabled = false
style = "#b0c4de"
time_format = "%Y/%m/%d %T"
format = "[$time]($style) "
