add_newline = false

[cmd_duration]
min_time = 0
show_milliseconds = true

[env_var]
variable = "SCRIPT_PS1"
default = "???"
style = "bold yellow"

[time]
disabled = false
style = "white"
time_format = "%F %T" # not work?
