.\" $Id$ -*-nroff-*-

.TH GIT-C 1

.SH NAME
git-c \- Commit changes without any editor

.SH SYNOPSIS
.B git c
[--with-guideline]
[--help]

.SH DESCRIPTION
Commit changes without any editor

.SH OPTIONS
.TP 4
.BI --with-guideline
Prints guideline for good commit message
.TP
.BI --help
Prints this help
