#!/bin/sh

COMMIT_MESSAGE_MAX_LENGTH=69

first_line=$(cat "$1" | grep -v '^#' | sed '/^$/d' | head -1)
first_line_length=${#first_line}

echo

if [ "$first_line_length" -gt $COMMIT_MESSAGE_MAX_LENGTH ]; then
  printf "\033[1;93m"
  echo "The commit summary exceeds $COMMIT_MESSAGE_MAX_LENGTH characters ($first_line_length characters)"
  echo "It may be truncated on GitHub"
  printf "\033[00m"
  printf "Are you sure you want to commit anyway? [y/N]: "

  exec < /dev/tty
  read -r confirm

  if [ "$confirm" != "Y" ] && [ "$confirm" != "Yes" ] && [ "$confirm" != "YES" ]; then
    printf "\033[1;91m\n"
    printf "Canceled\n"
    printf "\033[00m"

    exit 1
  fi
fi
