#!/bin/sh

# MEMO:
#   Just before the operation was...
#     commit:                               afb8378 (HEAD -> main, origin/main) HEAD@{0}: commit: 2022-02-15
#     pull:                                 4ea1572 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull: Fast-forward
#     cherry-pick (before --continue):      09410850a (HEAD -> release/app-20220214-2) HEAD@{0}: commit (cherry-pick): Fix RSpec failures
#     cherry-pick (--continue in progress): 04f16f396 HEAD@{0}: commit (cherry-pick): Fix RSpec failures
#     cherry-pick (after --continue):       119e7db53 (HEAD -> release/app-20220214-2) HEAD@{0}: cherry-pick: Add tests for recent_comment_counts

# Skip if cherry-picking
if git reflog -n 1 | grep -Eq '\(?cherry-pick\)?:'; then
  exit 0
fi

git --no-pager log -1

printf "\nCommitted as:\n"
printf "  (use \"git reset --soft HEAD^\" to undo)\n\n"
printf "	\033[1;93m%s <%s>\033[00m\n\n" "$(git config --local user.name)" "$(git config --local user.email)"
printf "\033[1;95mCheck if they are correct\033[00m\n\n"
