#!/bin/bash

echo -e "Committed as:"
echo -e "  (use \"git reset --soft HEAD^\" to undo)\n"
echo -e "	\033[1;93m`git config --local user.name` <`git config --local user.email`>\033[00m\n"
echo -e "\033[1;95mCheck if they are correct\033[00m\n"
