#!/bin/bash

# This script only reads other scripts in pre-push-before and pre-push-after directories.
# Because `read local_ref local_sha1 remote_ref remote_sha1` can be used only once.
# If `read local_ref local_sha1 remote_ref remote_sha1` is used in multiple scripts as pre-push,
# it does not work properly.
while read local_ref local_sha1 remote_ref remote_sha1
do
  for before_scripts in $(git rev-parse --git-dir)/hooks/pre-push-before/*
  do
    . $before_scripts
  done

  # The scripts in pre-push-after must be executed after the scripts in pre-push-before
  # because they contain `exit 0`, which means the hook script stops in the middle of execution.
  for after_scripts in $(git rev-parse --git-dir)/hooks/pre-push-after/*
  do
    . $after_scripts
  done
done
