#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
  echo -e  "You are about to push:\n"
  echo -e  "	\033[1;93m${local_ref##refs/heads/}\033[00m -> \033[1;93morigin/${remote_ref##refs/heads/}\033[00m\n"
  echo -en "Are you sure? [Y/n]: "

  exec < /dev/tty
  read confirm

  echo -e ""
  if [ $confirm = "Y" ] || [ $confirm = "Yes" ] || [ $confirm = "YES" ]; then
    echo -e "Pushing to \033[1;93m${local_ref##refs/heads/}\033[00m -> \033[1;93morigin/${remote_ref##refs/heads/}\033[00m"
    exit 0
  else
    echo -e "\033[1;91mCanceled\033[00m"
    exit 1
  fi
done
